"""added previous notes support

Revision ID: 603d83de7174
Revises: c280dbb6141e
Create Date: 2021-09-16 17:51:57.172921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603d83de7174'
down_revision = 'c280dbb6141e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previous_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_id'], ['note.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previous_note_created_on'), 'previous_note', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_previous_note_created_on'), table_name='previous_note')
    op.drop_table('previous_note')
    # ### end Alembic commands ###
