"""added last_edited_on

Revision ID: c280dbb6141e
Revises: dd5e7be985bd
Create Date: 2021-09-16 14:02:38.370932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c280dbb6141e'
down_revision = 'dd5e7be985bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('note', sa.Column('last_edited_on', sa.DateTime(), nullable=True))
    op.drop_index('ix_note_timestamp', table_name='note')
    op.create_index(op.f('ix_note_created_on'), 'note', ['created_on'], unique=False)
    op.create_index(op.f('ix_note_last_edited_on'), 'note', ['last_edited_on'], unique=False)
    op.drop_column('note', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_note_last_edited_on'), table_name='note')
    op.drop_index(op.f('ix_note_created_on'), table_name='note')
    op.create_index('ix_note_timestamp', 'note', ['timestamp'], unique=False)
    op.drop_column('note', 'last_edited_on')
    op.drop_column('note', 'created_on')
    # ### end Alembic commands ###
