"""empty message

Revision ID: dd5e7be985bd
Revises: d1fbf4cb06af
Create Date: 2021-09-16 12:39:43.891691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5e7be985bd'
down_revision = 'd1fbf4cb06af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('title', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'title')
    # ### end Alembic commands ###
